# Generated by Django 2.0.1 on 2018-10-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181023_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='resources/org/%Y/%m/%d', verbose_name='封面图'),
        ),
    ]
