# Generated by Django 2.0.1 on 2018-10-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181023_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='resources/courses/%Y/%m/%d', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='resources/courses/resource/%Y/%m/%d', verbose_name='资源文件'),
        ),
    ]
